apiVersion: v1
kind: ResourceQuota
metadata:
  name: devspaces-workspace-quota
  namespace: openshift-devspaces
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 32Gi
    limits.cpu: "16"
    limits.memory: 64Gi
    persistentvolumeclaims: "10"
